# Generated by Django 2.1.4 on 2019-03-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='counterparty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='sector',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
